---
title: "My resume"
author: Francisco d'Albertas Gomes de Carvalho
twitter: mariecurie
github: mariecurie
linkedin: mariecurie
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
    footer: "Copyright (c) 2014, RStudio"
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
---

Aside
================================================================================

Personal Info {#contact}
--------------------------------------------------------------------------------

- <i class="fas fa-birthday-cake"></i> September 17, 1986
- <i class="fas fa-map-pin"></i> Avenida IV Centenário, 231, casa c3, 04030-000, São Paulo, Brazil.
- <i class="fas fa-globe-americas"></i> Brazilian and French Nationality
- <i class="fa fa-envelope"></i> francisco.albertas@gmail.com
- <i class="fa fa-phone"></i> +55 11 99121-8851
- For more information, please contact me via email.

Social media {#contact}
--------------------------------------------------------------------------------
- <i class="fab fa-twitter"></i> [twitter.com/FdAlbertas](https://twitter.com/FdAlbertas)
- <i class="fab fa-researchgate"></i>[researchgate.net/profile](https://www.researchgate.net/profile/Francisco_Dalbertas_G_De_Carvalho)

Skills {#skills}
--------------------------------------------------------------------------------

### Coding

- R

### Software

- QGIS - ArcGIS

### Other

- statistical analysis - Geographic Information System - spatial analysis and modelling.


Languages {#skills}
--------------------------------------------------------------------------------

- Portuguese (native)
- English (fluent)
- French (advanced)
- Spanish (intermediate)

<!-- Disclaimer {#disclaimer} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- Francisco d'Albertas - Curriculum Vitae -->

<!-- Last updated on `r Sys.Date()`. -->


Main
================================================================================

Francisco d'Albertas Gomes de Carvalho {#title}
--------------------------------------------------------------------------------

### Landscape Ecologist

Biologist with a Master's thesis in Ecology and finishing a PhD in Landscape Ecology, my main expertise are related to landscape planning, spatial analysis and ecosystem services and in the interface between science, policy and impact evaluation. I am passionate about working on interdisciplinary subjects and committed to providing high quality service.

Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Environmental consultant

World Wildlife Fund - WWF Brazil

São Paulo, Brazil

2021-2020

- periodic analysis on deforestation and fire inside Protected Areas in the Amazon and Cerrado biomes, Brazil;


### Environmental consultant

Instituto Socioambiental - ISA

São Paulo, Brazil

2016

- Systematic mapping of pressures and threats to Brazilian State and Federal Protected Areas;


### Environmental consultant

Klabin s/a Paper and Cellulose

Paraná, Brazil

2016

- Planning of ecological corridors between indigenous lands as part of an Environmental Impact Assessment;

### Environmental consultant

Bloomberg Philanthropies e Global Road Safety

São Paulo, Brazil

2016

- Tree inventory data for urban planning in Sao Paulo;


### Junior environmental analyst, Internship

Instituto Socioambiental - ISA

São Paulo, Brazil

2013 - 2012

- Monitoring program on Protected Areas in the Amazon;

### Junior environmental analyst, Internship

Mineral Engenharia e Ambiente

São Paulo, Brazil

2012 - 2011

- Environmental Impact Analyses for mining and oil projects;

### Environmental manager, Internship

São Paulo Estate Secretary of Environment

São Paulo, Brazil

2010 - 2009

- Urban parks management;

### Environmental manager, Internship

São Paulo city Secretary of Environment

São Paulo, Brazil

2009 - 2008

- Urban parks management and environmental education;

Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

### Visiting student

University of Cambridge

Cambridge, United Kingdom

2021 - 2020

- Collaboration with Andrew Balmford's research group during 12 months to develop part of my PhD;
  


###  Research Assistant

Landscape Ecology and Conservation Lab (Department of Ecology, University of São Paulo), São Paulo, SP


São Paulo, Brazil

2017 - 2015

- São Paulo State Foundation (FAPESP) grant to join the Biodiversity and Ecosystem Service Scenarios Network (ScenNet);


Main Publications {data-icon=file}
--------------------------------------------------------------------------------

### Private reserves suffer from the same location biases of public Protected Areas

**d’Albertas, F.**, et al., Under review. *Biological Conservation*.

N/A

2021

### Gaps and limitations in the use of restoration scenarios: a review

Acosta, A.L., **d’Albertas, F.** et al., 2018. *Restoration Ecology* 26, 1108–1119. 

N/A

2018

### Lack of evidence of edge age and additive edge effects on carbon stocks in a tropical forest

**d’Albertas, F.**, et al., 2018. *Forest Ecology and Management* 407, 57–65. 


N/A

2018

### Best practice for the use of scenarios for restoration planning

Metzger, J.P., Esler, K., Krug, C., Arias, M., Tambosi, L., Crouzeilles, R., Acosta, A.L., Brancalion, P.H., **d’Albertas, F.** et al., 2017. *Current Opinion in Environmental Sustainability* 29, 14–25. 

N/A

2017


Presentations {data-icon=table data-concise=true}
--------------------------------------------------------------------------------

### Vegetation cover and land opportunity cost drive landowner’s willingness to set aside land for conservation

10th IALE World Congress

Milano, Italy

2019

### Systematic mapping of biodiversity and ecosystem services scenarios applied to environmental restoration

VII World Conference on Ecological Restoration

Foz do Iguaçu, Brazil

2017


### Carbon stocks in fragmented forests are extensively modulated by edge effects

Conference on Conservation Science-NY

New York, USA

2016


### Systematic mapping of biodiversity and ecosystem services scenarios applied to environmental restoration

International conference on scenarios and models of biodiversity and ecosystem services in support of decision making

Montpellier, France

2016

### Modulação do estoque de carbono em paisagens fragmentadas da Mata Atlântica em função dos efeitos de borda

IUFRO LE Latin-American and 2° IALE Latin-American Congress

Temuco, Chile

2016 


### *Modeling forest canopy closure using vegetation index*.

Simpósio Brasileiro de Sensoriamento Remoto

Foz do Iguaçu, Brazil

2013


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### University of São Paulo

PhD in Ecology

São Paulo, Brazil

2021 - 2017

Dissertation: Paths for the ecological intensification of agriculture (finishing in September)


### University of São Paulo

M.S. in Ecology

São Paulo, Brazil

2015 - 2013 

Thesis: Edge efects modulation of carbon stocks in fragmented Atlantic
forest landscapes

### University of São Paulo

B.S. in Biological Sciences

São Paulo, Brazil

2011 - 2006

Thesis: Modeling forest canopy closure using vegetation index


